In [1]:
import pandas as pd

In [12]:
df_pokemon = pd.read_csv('../data/pokemon.csv')

In [13]:
df_pokemon.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [11]:
df_columns = ['name', 'type1', 'type2', 'hp', 'attack', 
           'defense', 'sp_attack', 'sp_defense', 'speed', 
           'generation', 'is_legendary']

In [14]:
df_pokemon = df[df_columns]

In [17]:
df_pokemon.head()

,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,generation,is_legendary
0,Bulbasaur,grass,poison,45,49,49,65,65,45,1,0
1,Ivysaur,grass,poison,60,62,63,80,80,60,1,0
2,Venusaur,grass,poison,80,100,123,122,120,80,1,0
3,Charmander,fire,NaN,39,52,43,60,50,65,1,0
4,Charmeleon,fire,NaN,58,64,58,80,65,80,1,0

In [19]:
# Detectando se tem valores nulos
df_pokemon.isna().sum()

name              0
type1             0
type2           384
hp                0
attack            0
defense           0
sp_attack         0
sp_defense        0
speed             0
generation        0
is_legendary      0
dtype: int64

In [21]:
df_pokemon.type2.isna().sum()

np.int64(384)

In [22]:
df_pokemon[df_pokemon.isna().any(axis=1)]

,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,generation,is_legendary
3,Charmander,fire,NaN,39,52,43,60,50,65,1,0
4,Charmeleon,fire,NaN,58,64,58,80,65,80,1,0
6,Squirtle,water,NaN,44,48,65,50,64,43,1,0
7,Wartortle,water,NaN,59,63,80,65,80,58,1,0
8,Blastoise,water,NaN,79,103,120,135,115,78,1,0
...,...,...,...,...,...,...,...,...,...,...,...
781,Jangmo-o,dragon,NaN,45,55,65,45,45,45,7,0
788,Cosmog,psychic,NaN,43,29,31,29,31,37,7,1
789,Cosmoem,psychic,NaN,43,29,131,29,131,37,7,1
795,Xurkitree,electric,NaN,83,89,71,173,71,83,7,1
799,Necrozma,psychic,NaN,97,107,101,127,89,79,7,1

In [ ]:
# Coluna Type2 possui 384 linhas nulas, não é dado faltante é característica.

In [26]:
# Preenchendo onde estiver null com 'none' (tratando os dados nulos)

df_pokemon = df_pokemon.fillna(value={'type2': 'none'})

In [27]:
df_pokemon.head(10)

,name,type1,type2,hp,attack,defense,sp_attack,sp_defense,speed,generation,is_legendary
0,Bulbasaur,grass,poison,45,49,49,65,65,45,1,0
1,Ivysaur,grass,poison,60,62,63,80,80,60,1,0
2,Venusaur,grass,poison,80,100,123,122,120,80,1,0
3,Charmander,fire,none,39,52,43,60,50,65,1,0
4,Charmeleon,fire,none,58,64,58,80,65,80,1,0
5,Charizard,fire,flying,78,104,78,159,115,100,1,0
6,Squirtle,water,none,44,48,65,50,64,43,1,0
7,Wartortle,water,none,59,63,80,65,80,58,1,0
8,Blastoise,water,none,79,103,120,135,115,78,1,0
9,Caterpie,bug,none,45,30,35,20,20,45,1,0

In [28]:
## Checando os tipos de dados
df_pokemon.dtypes

name              str
type1             str
type2             str
hp              int64
attack          int64
defense         int64
sp_attack       int64
sp_defense      int64
speed           int64
generation      int64
is_legendary    int64
dtype: object

In [30]:
df_pokemon.to_csv('../data/pokemon_clean.csv', index=False)